### ISSUE TITLE
src/jaligner/ui/images/gifs/* are Copyright Sun and non-redistributable in Debian

### ISSUE THREAD

**Issue by mr-c** [ahmedmoustafa/JAligner#2]
Hello,

My name is Michael R. Crusoe and I've been working with the [Debian-Med team](https://www.debian.org/devel/debian-med/) to package jaligner for the Debian GNU/Linux distribution. 

The images in src/jaligner/ui/images/gifs/ are copyright Sun Microsystems. Do you have a license for them? We [made our own icons for now](http://anonscm.debian.org/cgit/debian-med/jaligner.git/tree/debian/images) but would prefer to not have to patch the source.

Cheers,

**Comment by ahmedmoustafa** [comment]
Hi Michael,
This is super exciting! :)
No, I do not have license for the gifs.
So, please go ahead and replace them with you the ones you created.
If there is something that I can help with packing jaligner in Debian-Med, please let me know!
Cheers,
Ahmed

**Comment by mr-c** [comment]
JAligner has been accepted into the Debian archive and will appear in the next stable release of Debian (and a future release of Debian derivatives like Ubuntu)

https://packages.debian.org/sid/jaligner

**Comment by mr-c** [comment]
It was fairly easy to package, the only changes we made were to replace the icons and write a minimal manual page ( http://anonscm.debian.org/cgit/debian-med/jaligner.git/tree/debian/jaligner.ronn using https://rtomayko.github.io/ronn/ronn.1.html )

Thank you for putting the source on GitHub! Much easier to automatically find releases than sourceforge.

**Comment by ahmedmoustafa** [comment]
Thank you so much Michael !! :smile: This is very exciting !!
